name: Build and Release

on:
  push:
    branches: [ "main", "master" ]
    tags:
      - 'v*'
  pull_request:
    branches: [ "main", "master" ]
  workflow_dispatch:
    inputs:
      build_config:
        description: 'Build configuration'
        required: true
        default: 'Release'
        type: choice
        options:
          - Release
          - Debug

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        
    - name: Restore dependencies
      run: dotnet restore PHelper.csproj
      
    - name: Publish
      run: dotnet publish PHelper.csproj --no-restore --configuration ${{ inputs.build_config || 'Release' }} -o ./publish
      
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4
      with:
        name: PHelper-${{ inputs.build_config || 'Release' }}
        path: ./publish/

  release:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/v')
    permissions:
      contents: write
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: PHelper-Release
        path: ./publish/
        
    - name: Zip files
      run: |
        cd publish
        zip -r ../PHelper.zip ./*
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: PHelper.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
